# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit

repos:
# Standard hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: sort-simple-yaml
  - id: file-contents-sorter
  - id: trailing-whitespace
    exclude: ^doc/_static/.*.svg

- repo: local
  hooks:
  - id: version-check
    name: version-check
    language: python
    additional_dependencies: [requests]
    entry: python .ci/version_check.py

# Python linter (Flake8)
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8

# Python formatting
- repo: https://github.com/psf/black
  rev: 21.5b1
  hooks:
  - id: black

# Python docstring formatting
- repo: https://github.com/pycqa/pydocstyle
  rev: 6.0.0
  hooks:
  - id: pydocstyle
    files: src/iminuit/[^_].*\.py

# C++ formatting
- repo: git://github.com/doublify/pre-commit-clang-format
  rev: 62302476d0da01515660132d76902359bed0f782
  hooks:
  - id: clang-format

# CMake formatting
- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.13
  hooks:
  - id: cmake-format
    additional_dependencies: [pyyaml]
    types: [file]
    files: (\.cmake|CMakeLists.txt)(.in)?$
