language: python

sudo: false

matrix:
    include:
        - python: 2.7
          env: BUILD=TEST

        - python: 3.4
          env: BUILD=TEST

        - python: 3.5
          env: BUILD=TEST

        # TODO: add tests for installed version!!

        # TODO: add tests on Mac

        # TODO: add tests for Python from conda

        - python: 2.7
          env: BUILD=DOCS

        - python: 3.4
          env: BUILD=DOCS

        - python: 3.5
          env: BUILD='COVERAGE'

        - python: 3.5
          env: BUILD=NO_EXTRA_DEPS


before_install:
  - pip install setuptools Cython
  - if [[ $BUILD != NO_EXTRA_DEPS ]]; then pip install IPython numpy matplotlib; fi
  - if [[ $BUILD == DOCS ]]; then pip install matplotlib sphinx sphinx_rtd_theme; fi
  - if [[ $BUILD == TEST ]] || [[ $BUILD == COVERAGE ]]; then pip install pytest pytest-cov numpy; fi

install:
  - python setup.py build_ext -i
  - python setup.py install

script:
  - if [[ $BUILD == TEST ]]; then make test; fi
  - if [[ $BUILD == COVERAGE ]]; then make coverage; fi
  - if [[ $BUILD == DOCS ]]; then cd doc; sphinx-build -W -a -E -b html -d _build/doctrees . _build/html; fi
