language: python
dist: xenial

# master is tested by Azure
branches:
  only:
    - develop

cache:
  pip: true
  directories:
    - pypy3.6

matrix:
  include:
    # main build where everything is tested and code coverage is generated
    - name: "3.7: test, doc, coverage"
      python: 3.7
      install:
        - pip install --upgrade -r requirements-dev.txt
        - pip install codecov ipykernel
        - python -m ipykernel install --user --name python3
      script:
        COVERAGE=1 make cov && make doc && codecov && python -m pytest tutorial && make code-analysis

    - name: "osx: test"
      os: osx
      language: sh
      install:
        pip install --user --upgrade -r .ci/requirements-test.txt
      script:
        make test

    - name: "pypy3.6: test"
      language: sh
      install:
        source .ci/install_pypy3.6.sh
      script:
        make test

    ## sdist tests are now done by Azure
    # - name: "2.7: sdist"
    #   python: 2.7
    #   script: .ci/travis_sdist_test.sh
    #
    # - name: "3.6: sdist"
    #   python: 3.6
    #   script: .ci/travis_sdist_test.sh
    #
    # - name: "3.7: sdist"
    #   python: 3.7
    #   script: .ci/travis_sdist_test.sh
