language: python

sudo: false

matrix:
    include:
        - python: 2.7

        - python: 3.5

        # TODO: add tests for installed version!!

        # TODO: add tests on Mac

        # TODO: add tests for Python from conda

        - python: 2.7
          env: DOCS=1

        - python: 3.5
          env: COVERAGE=1

        - python: 3.5
          env: NO_EXTRA_DEPS=1


before_script:
  - pip install setuptools Cython
  - if [[ ! $NO_EXTRA_DEPS ]]; then pip install IPython numpy matplotlib; fi
  - if [[ $COVERAGE ]]; then pip install pytest-cov; fi
  - if [[ $DOCS ]]; then
      pip install matplotlib sphinx sphinx_rtd_theme
    else # always test except for docs build
      pip install pytest
    fi

install:
  - make install

script:
  - if [[ ! $DOCS ]]; then # always test except when building docs
      if [[ $NO_EXTRA_DEPS ]]; then pip install numpy; fi # numpy required for testing
      make test
    fi
  - if [[ $COVERAGE ]]; then make coverage; fi
  - if [[ $DOCS ]]; then make doc; fi
