language: python

sudo: false

matrix:
  include:
    # TODO: remove "-dev" once 3.7 proper exists on travis-ci
    - python: 3.7-dev
      env: BUILD=TEST

    - python: 3.7-dev
      env: BUILD=SDIST

    - python: 3.7-dev
      env: BUILD=COVERAGE

    - python: 2.7
      env: BUILD=TEST

    - python: 2.7
      env: BUILD=SDIST

# TODO: add osx builds; (setting up multi-os envs isn't trivial, see below)
#        - os: osx
#          python: 2.7
#          env: BUILD=ALL
#
#        - os: osx
#          python: 3.5
#          env: BUILD=ALL
# https://docs.travis-ci.com/user/multi-os/
# This might also be useful:
# https://stackoverflow.com/questions/45257534/how-can-i-build-a-python-project-with-osx-environment-on-travis
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python  ; fi

install:
  - python ci-scripts/travis_install_deps.py;

script:
  - if [ $BUILD == TEST ]; then
      make test;
      make test-notebooks;
      make doc;
    fi
  - if [ $BUILD == COVERAGE ]; then
      make test;
      make test-notebooks;
      make coverage;
    fi
  - if [ $BUILD == SDIST ]; then source ci-scripts/travis_sdist_test.sh; fi
