language: python
dist: xenial

# master is tested by Azure
branches:
  only:
    - develop

cache:
  pip: true
  directories:
    - pypy3.6

matrix:
  include:
    # main build where everything is tested and code coverage is generated
    - name: "3.7: test, doc, coverage"
      python: 3.7
      install:
        - python -m pip install --upgrade -r requirements-dev.txt
        - python -m pip install codecov ipykernel
        - python -m ipykernel install --user --name python3
        - python -m pip install .
      script:
        COVERAGE=1 make cov && make doc && codecov && python -m pytest tutorial && make code-analysis

    - name: "osx: test"
      os: osx
      language: sh
      install:
        pip install --user --upgrade -r .ci/requirements-test.txt
      script:
        make test

    - name: "pypy3.6: test"
      language: sh
      install:
        source .ci/install_pypy36.sh
      script:
        make test
