[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "cmake",
    "numpy"
]
build-backend = "setuptools.build_meta"

[tool.nbqa.mutate]
black = 1

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-q -ra --ff"
testpaths = [
    "tests"
]

[tool.flake8]
max-line-length = 95
ignore = "E203,W503,E712"

[tool.pydocstyle]
convention = "numpy"
