on:
  pull_request:
    branches:
      - master
      - develop
    paths-ignore:
      - 'doc/**'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        python-version: [3.5, 3.8, pypy3]
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip install -r .ci/requirements-test.txt
    - name: Test
      run: pytest
  cov:
    runs-on: ubuntu-latest
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install -r requirements-dev.txt
        python -m ipykernel install --user --name python3
    - name: Test
      run: |
        COVERAGE=1 make analysis doc cov codecov
