name: CI

on:
  pull_request:
    # ci.yml tests everything except master, master is tested by wheels.yml
    branches-ignore:
      - master
    paths-ignore:
      - 'doc/**'
      - '.ci/**'
      - '*.rst'

jobs:
  cpython:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        python-version: [ '3.6', '3.9' ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - run: python -m pip install --upgrade pip wheel
    - run: python -m pip install .
    - run: python -m pip install pytest
    - run: python -m pytest

  pypy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v2
      with:
        python-version: pypy3
    - run: python -m pip install --upgrade pip wheel
    - run: python -m pip install .
    - run: python -m pip install pytest
    - run: python -m pytest
