name: CI

on:
  pull_request:
    branches:
      - develop
    paths-ignore:
      - 'doc/**'
      - '.ci/**'

jobs:
  cpython:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        python-version: [ '3.6', '3.9' ]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - run: python -m pip install --upgrade pip wheel
    - run: python -m pip install -r .ci/requirements-test.txt
    - run: python -m pip install .
    - run: python -m pytest

  pypy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v2
      with:
        python-version: pypy3
    - run: python -m pip install --upgrade pip wheel
    - run: python -m pip install numpy==1.15.4 pytest
    - run: python -m pip install .
    - run: python -m pytest
