name: Cov&Doc

on:
  pull_request:
    branches:
      - master
      - develop
    paths-ignore:
      - '.ci/**'

jobs:
  cpython:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install -r requirements-dev.txt
        python -m ipykernel install --user --name python3
    - run: pre-commit run -a
    - run:
        python -m pip install -e . -v
    - run: cd doc; make
    - run: python -m pytest tutorial
    - run: python -m pytest --cov src/iminuit
    - uses: AndreMiras/coveralls-python-action@develop
      with:
        debug: true
