name: Coverage

on:
  pull_request:
    branches:
      - master
      - develop
    paths-ignore:
      - '.ci/**'
  push:
    branches:
      - master
      - develop

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install -r requirements-dev.txt
    - run: pre-commit run -a
    - run: python -m pip install -e .
    - run: coverage run -m pytest
    - uses: AndreMiras/coveralls-python-action@develop
