name: Docs

on:
  pull_request:
    branches:
      - master
      - develop
    paths-ignore:
      - '.ci/**'
  push:
    branches:
      - master
      - develop

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements-dev.txt
        python -m ipykernel install --user --name python3
    - run: make doc
    - run: python -m pytest tutorial
