name: Docs

on:
  pull_request:
    paths-ignore:
      - '.ci/**'

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - run: |
        python -m pip install --upgrade pip
        python -m pip install .
        python -m pip install -r doc/rtd-pip-requirements
        python -m ipykernel install --user --name python3
    - run: make doc
    - run: python -m pip install .[test]
    - run: python -m pytest doc/tutorial
