on:
  pull_request:
    branches:
      - master
      - develop
    paths-ignore:
      - 'doc/**'

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v2
      with:
        python-version: 3.5
    - run: python -m pip install -r .ci/requirements-test.txt
    - run: python -m pip install -e .
    - run: pytest

  test_pypy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v2
      with:
        python-version: pypy3
    - run: python -m pip install --upgrade cython numpy==1.15.4 pytest
    - run: python -m pip install -e .
    - run: python -m pytest

  cov:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - run: |
        python -m pip install -r requirements-dev.txt
        python -m pip install codecov
        python -m ipykernel install --user --name python3
    - run: |
        COVERAGE=1 make analysis doc cov && codecov
