name: PyPI

on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: artifact
        path: dist

    - name: Prerelease
      if: "github.event.release.prerelease"
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{secrets.test_pypi_password}}
        repository_url: https://test.pypi.org/legacy/

    - name: Release
      if: "!github.event.release.prerelease"
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{secrets.pypi_password}}
