name: Release check

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  release_check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - run: python -m pip install requests
    - run: python .ci/release_check.py src/iminuit/version.py doc/changelog.rst
